=== jojev/xml-veb-servisi/official-backend/data/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" targetNamespace="http://www.ftn.uns.ac.rs/izvestaj_o_imunizaciji"
    xmlns="http://www.ftn.uns.ac.rs/izvestaj_o_imunizaciji">

    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="period">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="od" type="xs:date"/>
                            <xs:element name="do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="broj_interesovanja_o_imunizaciji">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_zahteva_za_digiatlni_sertifikat">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_izdatih_digitalnih_sertifikata">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_primljenih_doza_vakcina">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj_novo_vakcinisanih">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="raspodela_proizvodjaca">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="vakcina">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="tip" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_izdavanja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jojev/xml-veb-servisi/official-backend/data/documents/izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji
    xmlns="http://www.ftn.uns.ac.rs/izvestaj_o_imunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/izvestaj_o_imunizaciji
    ../schemes/izvestaj_o_imunizaciji.xsd"
    xmlns:pred="http://izvestaj-o-imunizaciji.com/#"
    about="http://izvjestaj-o-imunizaciji/identifikatorDokumenta/1"
    typeof="pred:IdentifikatorDokumenta">
    <period>
        <od property="pred:PeriodOdDatum">2021-08-01</od>
        <do property="pred:PeriodDoDatum">2021-09-01</do>
    </period>
    <broj_interesovanja_o_imunizaciji>2758</broj_interesovanja_o_imunizaciji>
    <broj_zahteva_za_digiatlni_sertifikat>453</broj_zahteva_za_digiatlni_sertifikat>
    <broj_izdatih_digitalnih_sertifikata>428</broj_izdatih_digitalnih_sertifikata>
    <broj_primljenih_doza_vakcina>3225</broj_primljenih_doza_vakcina>
    <broj_novo_vakcinisanih>1789</broj_novo_vakcinisanih>
    <raspodela_proizvodjaca>
        <vakcina tip="Pfizer, BioNTech">1625</vakcina>
        <vakcina tip="Sinopharm">1100</vakcina>
        <vakcina tip="Sputnik V">356</vakcina>
        <vakcina tip="AstraZeneca, Oxford">144</vakcina>
    </raspodela_proizvodjaca>
    <datum_izdavanja property="pred:IzdatDatuma" >2021-09-11</datum_izdavanja>
</izvestaj_o_imunizaciji>
