=== jojev/xml-veb-servisi/user-backend/data/schemes/obrazac_za_sprovodjenje_imunizacije.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije"
    xmlns="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije">

    <xs:element name="obrazac_za_sprovodjenje_imunizacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podaci_koje_je_popunio_pacijent">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="licni_podaci" type="osoba"/>
                            <xs:element name="saglasnost">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="SAGLASAN SAM"/>
                                        <xs:enumeration value="NISAM SAGLASAN"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="zeljena_vakcina">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="property"/>
                                            <xs:attribute name="datatype"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property"/>
                                            <xs:attribute name="datatype"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="podaci_koje_je_popunio_zdravstveni_radnik">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                            <xs:element name="vakcinacijski_punkt" type="xs:string"/>
                            <xs:element name="podaci_o_lekaru" type="xs:string"/>
                            <xs:element name="doze">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="doza" type="doza"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="privremene_kontraindikacije"
                                type="xs:string"/>
                            <xs:element minOccurs="0" name="odluka_komisije">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Da"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="interesovanje_ref">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property"/>
                                <xs:attribute name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about"/>
            <xs:attribute name="typeof"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="osoba">
        <xs:sequence>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                    <xs:element name="jmbg" type="jmbg"> </xs:element>
                </xs:sequence>
                <xs:sequence>
                    <xs:element name="strano_drzavljanstvo" type="xs:string"/>
                    <xs:element name="broj_pasosa">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string"/>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:choice>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="ime_roditelja" type="xs:string"/>
            <xs:element name="pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Z"/>
                        <xs:enumeration value="M"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum_rodjenja" type="xs:date"/>
            <xs:element name="mesto_rodjenja" type="xs:string"/>
            <xs:element name="adresa" type="podaci_o_adresi"/>
            <xs:element name="broj_fiksnog_telefona" type="xs:string"/>
            <xs:element name="broj_mobilnog_telefona" type="xs:string"/>
            <xs:element name="imejl" type="xs:string"/>
            <xs:element name="radni_status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="zaposlen"/>
                        <xs:enumeration value="nezaposlen"/>
                        <xs:enumeration value="penzioner"/>
                        <xs:enumeration value="ucenik"/>
                        <xs:enumeration value="student"/>
                        <xs:enumeration value="dete"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="zanimanje_zaposlenog">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="zdravstvena zastita"/>
                        <xs:enumeration value="socijalna zastita"/>
                        <xs:enumeration value="prosveta"/>
                        <xs:enumeration value="MUP"/>
                        <xs:enumeration value="Vojska RS"/>
                        <xs:enumeration value="drugo"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="korisnik_ustanove_socijalne_zastite">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="DA"/>
                        <xs:enumeration value="NE"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="naziv_sedista_ustanove" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="podaci_o_adresi">
        <xs:sequence>
            <xs:element name="ulica_broj" type="xs:string"/>
            <xs:element name="naselje" type="xs:string"/>
            <xs:element name="grad" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doza">
        <xs:sequence>
            <xs:element name="vakcina" type="xs:string"/>
            <xs:element name="datum_davanja_vakcine">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date">
                            <xs:attribute name="property"/>
                            <xs:attribute name="datatype"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element fixed="IM" name="nacin_davanja_vakcine" type="xs:string"/>
            <xs:element name="ekstremitet">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="DR"/>
                        <xs:enumeration value="LR"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="serija_vakcine" type="xs:string"/>
            <xs:element name="proizvodjac" type="xs:string"/>
            <xs:element name="nezeljena_reakcija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="jmbg">
        <xs:simpleContent>
            <xs:extension base="jmbg-restriction">
                <xs:attribute name="property" type="xs:string" use="required"/>
                <xs:attribute name="datatype"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="jmbg-restriction">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{13}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jojev/xml-veb-servisi/user-backend/data/documents/obrazac_za_sprovodjenje_imunizacije.xml
<?xml version="1.0" encoding="UTF-8"?>
<obrazac_za_sprovodjenje_imunizacije
    xmlns="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije
    ../schemes/obrazac_za_sprovodjenje_imunizacije.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/obrazac_za_sprovodjenje_imunizacije/predicate/"
    about="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije/1"
    typeof="pred:IdentifikatorDokumenta"
    referencira="http://www.ftn.uns.ac.rs/interesovanje/1">
    <podaci_koje_je_popunio_pacijent>
        <licni_podaci>
                <drzavljanstvo>Republike Srbije</drzavljanstvo>
                <jmbg property="pred:Kreirao">2412998125026</jmbg>
            <prezime>Filipovic</prezime>
            <ime>Dragana</ime>
            <ime_roditelja>Slobodan</ime_roditelja>
            <pol>Z</pol>
            <datum_rodjenja>2021-12-24</datum_rodjenja>
            <mesto_rodjenja>Doboj</mesto_rodjenja>
            <adresa>
                <ulica_broj>Boze Kuzmanovica 82</ulica_broj>
                <naselje>Klisa</naselje>
                <grad>Novi Sad</grad>
            </adresa>
            <broj_fiksnog_telefona>0212672829</broj_fiksnog_telefona>
            <broj_mobilnog_telefona>0652527924</broj_mobilnog_telefona>
            <imejl>dragana@gmail.com</imejl>
            <radni_status>student</radni_status>
            <korisnik_ustanove_socijalne_zastite>DA</korisnik_ustanove_socijalne_zastite>
            <naziv_sedista_ustanove>Novi Sad</naziv_sedista_ustanove>
        </licni_podaci>
        <saglasnost>SAGLASAN SAM</saglasnost>
        <zeljena_vakcina property="pred:ZeljenaVakcina">Pfizer, BioNTech</zeljena_vakcina>
        <datum property="pred:KreiranDatuma">2021-06-11</datum>
    </podaci_koje_je_popunio_pacijent>
    <podaci_koje_je_popunio_zdravstveni_radnik>
        <zdravstvena_ustanova>Dom zdravlja Novi Sad</zdravstvena_ustanova>
        <vakcinacijski_punkt>Promenada</vakcinacijski_punkt>
        <podaci_o_lekaru>Pera Peric 06532984920</podaci_o_lekaru>
        <doze>
            <doza>
                <vakcina>Pfizer, BioNTech</vakcina>
                <datum_davanja_vakcine property="pred:VakcinisanDatuma">2021-06-11</datum_davanja_vakcine>
                <nacin_davanja_vakcine>IM</nacin_davanja_vakcine>
                <ekstremitet>DR</ekstremitet>
                <serija_vakcine>FC3098</serija_vakcine>
                <proizvodjac>BioNTech</proizvodjac>
                <nezeljena_reakcija>mucnina</nezeljena_reakcija>
            </doza>
        </doze>
    </podaci_koje_je_popunio_zdravstveni_radnik>
</obrazac_za_sprovodjenje_imunizacije>
