=== jojev/xml-veb-servisi/official-backend/data/schemes/potvrda_o_vakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji">

    <xs:element name="potvrda_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sifra_potvrde_vakcinacije">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{7}-\d{7}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="licni_podaci" type="osoba"/>
                <xs:element name="podaci_o_vakcinaciji" type="vakcinacija"/>
                <xs:element name="datum_izdavanja_potvrde" type="xs:date"/>
                <xs:element name="qr-kod" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="osoba">
        <xs:sequence>
            <xs:element name="ime_prezime" type="xs:string"/>
            <xs:element name="datum_rodjenja" type="xs:date"/>
            <xs:element name="pol">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Musko"/>
                        <xs:enumeration value="Zensko"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vakcinacija">
        <xs:sequence>
            <xs:element name="doze">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="doza" type="doza"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="zdravstvena_ustanova" type="xs:string"/>
            <xs:element name="naziv_vakcine" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="doza">
        <xs:sequence>
            <xs:element name="datum_davanja" type="xs:date"/>
            <xs:element name="serija" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="redni_broj">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== jojev/xml-veb-servisi/official-backend/data/documents/potvrda_o_vakcinaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrda_o_vakcinaciji
    xmlns="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji
    ../schemes/potvrda_o_vakcinaciji.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/potvrda_o_vakcinaciji/predicate/"
    about="http://www.ftn.uns.ac.rs/potvrda_o_vakcinaciji/1" typeof="pred:IdentifikatorDokumenta"
    referencira="http://www.ftn.uns.ac.rs/obrazac_za_sprovodjenje_imunizacije/1">
    <sifra_potvrde_vakcinacije>1234567-7654321</sifra_potvrde_vakcinacije>
    <licni_podaci>
        <ime_prezime>Dragana Filipovic</ime_prezime>
        <datum_rodjenja>1998-12-24</datum_rodjenja>
        <pol>Zensko</pol>
        <jmbg property="pred:KreiranZa">2412998125026</jmbg>
    </licni_podaci>
    <podaci_o_vakcinaciji>
        <doze>
            <doza redni_broj="1">
                <datum_davanja>2021-02-07</datum_davanja>
                <serija>
                    FC3098
                </serija>
            </doza>
            <doza redni_broj="2">
                <datum_davanja>2021-07-23</datum_davanja>
                <serija>
                    FC3143
                </serija>
            </doza>
        </doze>
        <zdravstvena_ustanova>
            Dom zdravlja "Novi Sad", Novi Sad
        </zdravstvena_ustanova>
        <naziv_vakcine>
            Pfizer BioNTech COVID-19 Vaccine
        </naziv_vakcine>
    </podaci_o_vakcinaciji>
    <datum_izdavanja_potvrde property="pred:Izdat">2021-07-02</datum_izdavanja_potvrde>
    <qr-kod property="pred:Linkuje">
        url.com
    </qr-kod>
</potvrda_o_vakcinaciji>
