=== jojev/xml-veb-servisi/official-backend/data/schemes/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
     elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat"
    xmlns="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat">

    <xs:element name="zahtev_za_izdavanje_sertifikata">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnosilac_zahteva" type="osoba"/>
                <xs:element name="razlog_za_podnosenje" type="xs:string"/>
                <xs:element name="mesto_podnosenja_zahteva" type="xs:string"/>
                <xs:element name="datum_podnosenja_zahteva" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="osoba">
        <xs:sequence>
            <xs:element name="ime_prezime" type="xs:string"/>
            <xs:element name="datum_rodjenja">
                <xs:simpleType>
                    <xs:restriction base="xs:date">
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pol" type="pol"/>
            <xs:element name="jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_pasosa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="9"/>
                        <xs:pattern value="\d{9}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType final="" name="pol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Zenski"/>
            <xs:enumeration value="Muski"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jojev/xml-veb-servisi/xml_dokumenti/zahtev_za_izdavanje_sertifikata.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_izdavanje_sertifikata
    xmlns="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat
    ../xml_sheme/zahtev_za_sertifikat.xsd">
    <podnosilac_zahteva>
        <ime_prezime>Dragana Filipovic</ime_prezime>
        <datum_rodjenja>1998-12-24</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg>1234567891234</jmbg>
        <broj_pasosa>123456789</broj_pasosa>
    </podnosilac_zahteva>
    <razlog_za_podnosenje>razlog podnosenja zahteva</razlog_za_podnosenje>
    <mesto_podnosenja_zahteva>Novi Sad</mesto_podnosenja_zahteva>
    <datum_podnosenja_zahteva>2021-06-12</datum_podnosenja_zahteva>
</zahtev_za_izdavanje_sertifikata>

=== jojev/xml-veb-servisi/official-backend/data/documents/zahtev_za_izdavanje_sertifikata.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_izdavanje_sertifikata
    xmlns="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat
    ../schemes/zahtev_za_sertifikat.xsd"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/zahtev_za_sertifikat/predicate/"
    about="http://www.ftn.uns.ac.rs/zahtev_za_sertifikat/1"
    typeof="pred:IdentifikatorDokumenta">
    <podnosilac_zahteva>
        <ime_prezime>Dragana Filipovic</ime_prezime>
        <datum_rodjenja>1998-12-24</datum_rodjenja>
        <pol>Muski</pol>
        <jmbg property="pred:PodneoJmbg">1234567891234</jmbg>
        <broj_pasosa property="pred:PodneoBrPasosa">123456789</broj_pasosa>
    </podnosilac_zahteva>
    <razlog_za_podnosenje>razlog podnosenja zahteva</razlog_za_podnosenje>
    <mesto_podnosenja_zahteva>Novi Sad</mesto_podnosenja_zahteva>
    <datum_podnosenja_zahteva property="pred:IzdatDatuma">2021-06-12</datum_podnosenja_zahteva>
</zahtev_za_izdavanje_sertifikata>
